-- MySQL Script generated by MySQL Workbench
-- Sat Feb 20 21:45:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`voiture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`voiture` (
  `matricule` INT NOT NULL,
  `nb_place` INT NOT NULL,
  `nb_porte` INT NOT NULL,
  `type_boite` VARCHAR(15) NOT NULL,
  `espace` INT(1) NOT NULL,
  `climatisation` INT(1) NOT NULL DEFAULT 1,
  `prix` INT NOT NULL,
  `marque` VARCHAR(20) NOT NULL,
  `modele` VARCHAR(45) NOT NULL,
  `image` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`matricule`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `cin` INT(8) NOT NULL,
  `nom` VARCHAR(25) NOT NULL,
  `prenom` VARCHAR(25) NOT NULL,
  `dn` DATE NOT NULL,
  `email` VARCHAR(85) NOT NULL,
  `tel` INT(8) NOT NULL,
  `adresse` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`cin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `username` VARCHAR(25) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  `voiture_matricule` INT NOT NULL,
  PRIMARY KEY (`username`, `voiture_matricule`),
  INDEX `fk_admin_voiture1_idx` (`voiture_matricule` ASC) VISIBLE,
  CONSTRAINT `fk_admin_voiture1`
    FOREIGN KEY (`voiture_matricule`)
    REFERENCES `mydb`.`voiture` (`matricule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `voiture_matricule` INT NOT NULL,
  `client_cin` INT(8) NOT NULL,
  `date_debut` DATE NOT NULL,
  `date_fin` DATE NOT NULL,
  PRIMARY KEY (`voiture_matricule`, `client_cin`),
  INDEX `fk_voiture_has_client_client1_idx` (`client_cin` ASC) VISIBLE,
  INDEX `fk_voiture_has_client_voiture_idx` (`voiture_matricule` ASC) VISIBLE,
  CONSTRAINT `fk_voiture_has_client_voiture`
    FOREIGN KEY (`voiture_matricule`)
    REFERENCES `mydb`.`voiture` (`matricule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voiture_has_client_client1`
    FOREIGN KEY (`client_cin`)
    REFERENCES `mydb`.`client` (`cin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
